language: python
python:
  - "2.7"
before_install:
  - "ci/travis.sh"   
  - "pip install -r requirements.txt"
install:
  - "pip install flake8 python-coveralls"
script: python setup.py nosetests
after_success: coveralls
