language: python
python:
  - "2.7"
  - "pypy"
before_install:
  - "pip install -r requirements.txt"
  - "sudo apt-get install g++"
install:
  - "pip install flake8 python-coveralls"
script: python setup.py nosetests
after_success: coveralls
